# Generated by Django 5.2.7 on 2025-10-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('minimum_charge', models.DecimalField(decimal_places=2, help_text='The lowest price for this activity', max_digits=10, verbose_name='Minimum Charge')),
                ('currency', models.CharField(choices=[('JPY', '¥ JPY'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='JPY', max_length=3, verbose_name='Currency')),
                ('help_text', models.TextField(blank=True, help_text='Additional guidance or notes for customers', verbose_name='Help Text')),
                ('price_included', models.TextField(blank=True, help_text='What is included in the price (e.g., meals, equipment)', verbose_name='Price Included')),
                ('provider', models.CharField(blank=True, help_text='Company or person offering the activity', max_length=100, verbose_name='Provider')),
                ('location', models.CharField(help_text='General area or venue name', max_length=100, verbose_name='Location')),
                ('participants', models.CharField(blank=True, help_text='Possible number of bookings', max_length=50, verbose_name='Participants')),
                ('participating_age', models.CharField(blank=True, help_text='e.g., 6+, 18+, All ages', max_length=50, verbose_name='Participating Age')),
                ('duration', models.CharField(help_text='e.g., 2 hours, Half day, 3 days', max_length=100, verbose_name='Duration')),
                ('description', models.TextField(help_text='Full description of the activity', verbose_name='Description')),
                ('plan', models.CharField(help_text='Package options', max_length=100, verbose_name='Plan')),
                ('price', models.CharField(help_text='Pricing tiers', max_length=100, verbose_name='Price')),
                ('summary', models.TextField(blank=True, help_text='Short highlight or tagline', verbose_name='Summary')),
                ('min_p', models.PositiveIntegerField(help_text='Minimum required to run the activity', verbose_name='Min. Participants')),
                ('period', models.CharField(blank=True, help_text='e.g., Year-round, Summer only', max_length=100, verbose_name='Period')),
                ('deadline', models.DateTimeField(blank=True, help_text='Booking deadline', null=True, verbose_name='Deadline')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('map_id', models.CharField(blank=True, help_text='Google Maps Place ID or custom ID', max_length=100, verbose_name='Map ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Image',
                'verbose_name_plural': 'Activity Images',
                'ordering': ['order'],
            },
        ),
    ]
