# Generated by Django 5.2.7 on 2025-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='summary',
        ),
        migrations.AddField(
            model_name='activity',
            name='plan_1',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='plan_2',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='plan_3',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_1',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_2',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_3',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary_1',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary_2',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary_3',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deadline',
            field=models.CharField(blank=True, help_text='Booking deadline', max_length=100, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional guidance or notes for customers', max_length=100, verbose_name='Help Text'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
