# Generated by Django 5.2.7 on 2025-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_plan_remove_activity_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minimum_charge',
            field=models.CharField(help_text='The lowest price for this activity', max_length=100, verbose_name='Minimum Charge'),
        ),
    ]
