# Generated by Django 5.2.7 on 2025-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_address_alter_activity_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_p',
            field=models.CharField(blank=True, help_text='Minimum required to run the activity', max_length=100, verbose_name='Min. Participants'),
        ),
    ]
