# Generated by Django 5.2.7 on 2025-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_address_alter_activity_min_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='plan_1',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan_2',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan_3',
            field=models.CharField(blank=True, help_text='Package options', max_length=100, verbose_name='Plan 3'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_1',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_2',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_3',
            field=models.CharField(blank=True, help_text='Pricing tiers', max_length=100, verbose_name='Price 3'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_1',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_2',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_3',
            field=models.CharField(blank=True, help_text='Short highlight or tagline', max_length=100, verbose_name='Summary 3'),
        ),
    ]
