# Generated by Django 5.2.7 on 2025-10-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_plan_1_alter_activity_plan_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 2 hours, Half day, 3 days', max_length=100, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, help_text='General area or venue name', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_p',
            field=models.CharField(blank=True, help_text='Minimum required to run the activity', max_length=100, verbose_name='Min. P'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.TextField(verbose_name='Title (Very Very Very Very Very Very Very Long)'),
        ),
    ]
