# Generated by Django 5.2.7 on 2025-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_duration_alter_activity_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='deadline',
            new_name='reg_deadline',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='period',
        ),
        migrations.AddField(
            model_name='activity',
            name='event_ends',
            field=models.DateField(blank=True, null=True, verbose_name='Event Ends'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minimum_charge',
            field=models.CharField(max_length=100, verbose_name='Minimum Charge'),
        ),
    ]
