# Generated by Django 5.2.7 on 2025-10-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_deadline_activity_reg_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('hands_on', 'Hands-on'), ('performance', 'Performance'), ('exhibition', 'Exhibition'), ('lecture', 'Lecture'), ('workshop', 'Workshop')], default='gendai_to', max_length=20, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reg_deadline',
            field=models.CharField(blank=True, help_text='Registration Deadline', max_length=100, null=True, verbose_name='Deadline'),
        ),
    ]
