# Generated by Django 5.2.7 on 2025-10-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
