# Generated by Django 5.2.7 on 2025-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='minimum_charge',
            field=models.IntegerField(max_length=100, verbose_name='Minimum Charge'),
        ),
    ]
