# Generated by Django 5.2.7 on 2025-10-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_activity_minimum_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='minimum_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Charge'),
        ),
    ]
