# Generated by Django 5.2.7 on 2025-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_alter_activity_minimum_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='minimum_charge',
        ),
        migrations.AddField(
            model_name='activity',
            name='minimum_charge_numeric',
            field=models.IntegerField(blank=True, db_column='minimum_charge_numeric', null=True, verbose_name='Minimum Charge (Numeric)'),
        ),
    ]
