# Generated by Django 5.2.7 on 2025-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_remove_activity_minimum_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='minimum_charge_numeric',
        ),
        migrations.AddField(
            model_name='activity',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Charge'),
        ),
    ]
