# Generated by Django 5.2.7 on 2025-10-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='activities.activity'),
        ),
    ]
