# Generated by Django 6.0 on 2026-01-21 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Name (JP)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider')),
                ('signature', models.CharField(max_length=100, verbose_name='Signature (Mei)')),
                ('type', models.CharField(choices=[('katana', 'Katana'), ('tachi', 'Tachi'), ('wakizashi', 'Wakizashi'), ('kodachi', 'Kodachi'), ('tanto', 'Tanto')], max_length=20, verbose_name='Type')),
                ('blade_length', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Blade Length (cm)')),
                ('curvature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Curvature (cm)')),
                ('sword_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sword Weight (g)')),
                ('motohaba', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Motohaba (cm)')),
                ('sakihaba', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sakihaba (cm)')),
                ('motogasane', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Motogasane (cm)')),
                ('sakigasane', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sakigasane (cm)')),
                ('period_type', models.CharField(choices=[('koto', 'Koto'), ('chūkoto', 'Chūkoto'), ('shinto', 'Shinto'), ('gendai_to', 'Gendai-to')], help_text='pre-1500, 1500~1596, 1596~1867, 1868~', max_length=20, verbose_name='Period Type')),
                ('period', models.CharField(max_length=100, verbose_name='Period')),
                ('koshirae', models.CharField(max_length=100, verbose_name='Koshirae')),
                ('registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration')),
                ('certificate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificate')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('currency', models.CharField(choices=[('JPY', '¥ JPY'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='JPY', max_length=3, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collection')),
            ],
            options={
                'verbose_name': 'Collection Image',
                'verbose_name_plural': 'Collection Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('wire_transfer', 'Wire Transfer'), ('credit_card', 'Credit Card')], default='wire_transfer', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_order', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='collection.collection')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
