# Generated by Django 5.2.7 on 2025-10-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100, verbose_name='Name (JP)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider')),
                ('signature', models.CharField(blank=True, max_length=100, verbose_name='Signature (Mei)')),
                ('type', models.CharField(choices=[('刀', '刀 (Katana)'), ('脇差', '脇差 (Wakizashi)'), ('短刀', '短刀 (Tanto)'), ('太刀', '太刀 (Tachi)'), ('薙刀', '薙刀 (Naginata)'), ('槍', '槍 (Yari)'), ('他の', '他の (Other)')], default='刀', max_length=20, verbose_name='Type')),
                ('blade_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Blade Length (cm)')),
                ('curvature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Curvature (cm)')),
                ('sword_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (g)')),
                ('motohaba', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Motohaba (cm)')),
                ('sakihaba', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sakihaba (cm)')),
                ('motogasane', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Motogasane (cm)')),
                ('sakigasane', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sakigasane (cm)')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Period')),
                ('koshirae', models.TextField(blank=True, verbose_name='Koshirae')),
                ('registration', models.CharField(blank=True, max_length=100, verbose_name='Registration')),
                ('certificate', models.CharField(blank=True, max_length=100, verbose_name='Certificate')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price')),
                ('currency', models.CharField(choices=[('JPY', '¥ JPY'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='JPY', max_length=3, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/%Y/%m/%d/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collection')),
            ],
            options={
                'verbose_name': 'Collection Image',
                'verbose_name_plural': 'Collection Images',
                'ordering': ['order'],
            },
        ),
    ]
