# Generated by Django 6.0 on 2026-02-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tachi', 'Tachi'), ('katana', 'Katana'), ('kodachi', 'Kodachi'), ('wakizashi', 'Wakizashi'), ('tanto', 'Tanto')], max_length=10, verbose_name='type')),
                ('name_jp', models.CharField(max_length=100, verbose_name='name (JP)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (EN)')),
                ('provider', models.CharField(max_length=100, verbose_name='provider')),
                ('signature', models.CharField(max_length=100, verbose_name='signature (Mei)')),
                ('currency', models.CharField(choices=[('JPY', '¥ JPY'), ('USD', '$ USD'), ('EUR', '€ EUR')], max_length=3, verbose_name='currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price')),
                ('blade_length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='blade length (cm)')),
                ('curvature', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='curvature (cm)')),
                ('sword_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sword weight (g)')),
                ('motohaba', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='motohaba (cm)')),
                ('sakihaba', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sakihaba (cm)')),
                ('motogasane', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='motogasane (cm)')),
                ('sakigasane', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sakigasane (cm)')),
                ('period_type', models.CharField(choices=[('koto', 'Koto'), ('chūkoto', 'Chūkoto'), ('shinto', 'Shinto'), ('gendaito', 'Gendaito')], help_text='pre-1500, 1500~1596, 1596~1867, 1868~', max_length=20, verbose_name='period type')),
                ('period', models.CharField(max_length=100, verbose_name='period')),
                ('koshirae', models.CharField(default='Shirasaya', max_length=100, verbose_name='koshirae')),
                ('registration', models.CharField(default='－', max_length=100, verbose_name='registration')),
                ('certificate', models.CharField(default='－', max_length=100, verbose_name='certificate')),
                ('remarks', models.TextField(default='－', verbose_name='remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collection', verbose_name='activity images')),
            ],
            options={
                'verbose_name': 'collection image',
                'verbose_name_plural': 'collection images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100, verbose_name='name (JP)')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('payment', models.CharField(max_length=100, verbose_name='payment method')),
                ('address', models.TextField(verbose_name='delivery address')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('collection_id', models.CharField(max_length=10, verbose_name='collection id')),
                ('collection_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='collection.collection')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
