# Generated by Django 5.2.7 on 2025-10-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='koshirae',
            field=models.CharField(blank=True, max_length=100, verbose_name='Koshirae'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sword_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sword Weight (g)'),
        ),
    ]
