# Generated by Django 5.2.7 on 2025-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='period_type',
            field=models.CharField(choices=[('koto', 'Koto'), ('chūkoto', 'Chūkoto'), ('shinto', 'Shinto'), ('gendai_to', 'Gendai-to')], default='gendai_to', max_length=20, verbose_name='Period Type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('katana', 'Katana'), ('tachi', 'Tachi'), ('wakizashi', 'Wakizashi'), ('kodachi', 'Kodachi'), ('tanto', 'Tanto')], default='katana', max_length=20, verbose_name='Type'),
        ),
    ]
