# Generated by Django 6.0 on 2026-02-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'ordering': ['order'], 'verbose_name': 'collection image', 'verbose_name_plural': 'collection images'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_en',
            field=models.TextField(verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name_jp',
            field=models.TextField(verbose_name='Name (JP)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('katana', 'Katana'), ('tachi', 'Tachi'), ('kodachi', 'Kodachi'), ('wakizashi', 'Wakizashi'), ('tanto', 'Tanto')], max_length=20, verbose_name='collection type'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.collection', verbose_name='activity images'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(upload_to='collections/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='order'),
        ),
    ]
