# Generated by Django 5.2.7 on 2025-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('katana', 'Katana'), ('tachi', 'Tachi'), ('wakizashi', 'Wakizashi'), ('kodachi', 'Kodachi'), ('tanto', 'Tanto')], max_length=20, verbose_name='Type'),
        ),
    ]
