# Generated by Django 5.2.7 on 2025-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_period_type_alter_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='period_type',
            field=models.CharField(choices=[('koto', 'Koto'), ('chūkoto', 'Chūkoto'), ('shinto', 'Shinto'), ('gendai_to', 'Gendai-to')], default='gendai_to', help_text='pre-1500, 1500~1596, 1596~1867, 1868~', max_length=20, verbose_name='Period Type'),
        ),
    ]
