# Generated by Django 5.2.7 on 2025-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_period_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price'),
        ),
    ]
