# Generated by Django 5.2.7 on 2025-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration'),
        ),
    ]
