# Generated by Django 5.2.7 on 2025-10-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_order_options_alter_order_item_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_order',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
