# Generated by Django 5.2.7 on 2025-10-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
    ]
