# Generated by Django 6.0 on 2026-02-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('hands_on', 'Hands-on'), ('workshop', 'Workshop'), ('exhibition', 'Exhibition'), ('performance', 'Performance')], max_length=11, verbose_name='type')),
                ('title', models.TextField(verbose_name='title')),
                ('is_appointment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='is appointment')),
                ('currency', models.CharField(choices=[('JPY', '¥ JPY'), ('USD', '$ USD'), ('EUR', '€ EUR')], max_length=3, verbose_name='currency')),
                ('minimum_charge', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='minimum charge')),
                ('fee_details', models.CharField(max_length=100, verbose_name='fee details')),
                ('price_included', models.TextField(default='－', verbose_name='price included')),
                ('provider', models.CharField(max_length=100, verbose_name='provider')),
                ('participants', models.CharField(default='－', max_length=50, verbose_name='participants')),
                ('target_age', models.CharField(default='－', max_length=50, verbose_name='participating Age')),
                ('duration', models.CharField(default='－', max_length=100, verbose_name='duration')),
                ('description', models.TextField(verbose_name='description')),
                ('plan_1', models.CharField(blank=True, max_length=100, verbose_name='plan 1')),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 1')),
                ('summary_1', models.CharField(blank=True, max_length=100, verbose_name='summary 1')),
                ('plan_2', models.CharField(blank=True, max_length=100, verbose_name='plan 2')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 2')),
                ('summary_2', models.CharField(blank=True, max_length=100, verbose_name='summary 2')),
                ('plan_3', models.CharField(blank=True, max_length=100, verbose_name='plan 3')),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 3')),
                ('summary_3', models.CharField(blank=True, max_length=100, verbose_name='summary 3')),
                ('min_p', models.CharField(default='－', max_length=100, verbose_name='min participants')),
                ('reg_deadline', models.CharField(default='－', max_length=100, verbose_name='deadline')),
                ('event_ends', models.DateField(verbose_name='event ends')),
                ('prefecture', models.CharField(choices=[('hokkaido', 'Hokkaido'), ('aomori', 'Aomori'), ('iwate', 'Iwate'), ('miyagi', 'Miyagi'), ('akita', 'Akita'), ('yamagata', 'Yamagata'), ('fukushima', 'Fukushima'), ('ibaraki', 'Ibaraki'), ('tochigi', 'Tochigi'), ('gunma', 'Gunma'), ('saitama', 'Saitama'), ('chiba', 'Chiba'), ('tokyo', 'Tokyo'), ('kanagawa', 'Kanagawa'), ('niigata', 'Niigata'), ('toyama', 'Toyama'), ('ishikawa', 'Ishikawa'), ('fukui', 'Fukui'), ('yamanashi', 'Yamanashi'), ('nagano', 'Nagano'), ('gifu', 'Gifu'), ('shizuoka', 'Shizuoka'), ('aichi', 'Aichi'), ('mie', 'Mie'), ('shiga', 'Shiga'), ('kyoto', 'Kyoto'), ('osaka', 'Osaka'), ('hyogo', 'Hyogo'), ('nara', 'Nara'), ('wakayama', 'Wakayama'), ('tottori', 'Tottori'), ('shimane', 'Shimane'), ('okayama', 'Okayama'), ('hiroshima', 'Hiroshima'), ('yamaguchi', 'Yamaguchi'), ('tokushima', 'Tokushima'), ('kagawa', 'Kagawa'), ('ehime', 'Ehime'), ('kochi', 'Kochi'), ('fukuoka', 'Fukuoka'), ('saga', 'Saga'), ('nagasaki', 'Nagasaki'), ('kumamoto', 'Kumamoto'), ('oita', 'Oita'), ('miyazaki', 'Miyazaki'), ('kagoshima', 'Kagoshima'), ('okinawa', 'Okinawa')], max_length=20, verbose_name='prefecture')),
                ('lat', models.CharField(max_length=20, verbose_name='latitude')),
                ('lng', models.CharField(max_length=20, verbose_name='longitude')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('map_id', models.CharField(max_length=100, verbose_name='map id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activity.activity', verbose_name='activity images')),
            ],
            options={
                'verbose_name': 'activity image',
                'verbose_name_plural': 'activity images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200, verbose_name='activity')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('prefer_date', models.DateField(verbose_name='preferred date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('activity_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='activity.activity')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
