# Generated by Django 5.2.7 on 2025-10-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('hands_on', 'Hands-on'), ('performance', 'Performance'), ('exhibition', 'Exhibition'), ('lecture', 'Lecture'), ('workshop', 'Workshop')], max_length=20, verbose_name='Activity Type'),
        ),
    ]
