# Generated by Django 6.0 on 2026-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='participating_age',
            new_name='target_age',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('hands_on', 'Hands-on'), ('performance', 'Performance'), ('exhibition', 'Exhibition'), ('workshop', 'Workshop'), ('lecture', 'Lecture')], max_length=20, verbose_name='activity type'),
        ),
    ]
