# Generated by Django 5.2.7 on 2025-11-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.CharField(blank=True, help_text='Possible number of bookings', max_length=50, verbose_name='Participants'),
        ),
    ]
