# Generated by Django 5.2.7 on 2025-11-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_options_alter_activity_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_appointment',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True, verbose_name='Is Appointment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
