# Generated by Django 6.0 on 2026-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_participating_age_activity_target_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='price 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='price 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='price 3'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('hands_on', 'Hands-on'), ('workshop', 'Workshop'), ('exhibition', 'Exhibition'), ('performance', 'Performance')], max_length=20, verbose_name='activity type'),
        ),
    ]
