# Generated by Django 6.0 on 2026-02-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_price_1_alter_activity_price_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='price 3'),
        ),
    ]
