# Generated by Django 5.2.7 on 2025-11-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_is_appointment_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='help_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Help Text'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_p',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Min. P'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participating_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Participating Age'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plan_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan 3'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Price 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Price 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Price 3'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_included',
            field=models.TextField(blank=True, verbose_name='Price Included'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reg_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Summary 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Summary 2'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Summary 3'),
        ),
    ]
