# Generated by Django 6.0 on 2026-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kenshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='kenjyutsuka/images/%Y/%m/%d/', verbose_name='image')),
                ('video', models.FileField(upload_to='kenjyutsuka/videos/%Y/%m/%d/', verbose_name='video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kenshi',
                'verbose_name_plural': 'kenjyutsuka',
                'ordering': ['-created_at'],
            },
        ),
    ]
