# Generated by Django 5.2.7 on 2025-11-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kenshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('contents_main', models.TextField(blank=True, verbose_name='contents main')),
                ('subtitle_1', models.CharField(blank=True, max_length=100, verbose_name='subtitle 1')),
                ('contents_1', models.TextField(blank=True, verbose_name='contents 1')),
                ('video', models.FileField(blank=True, help_text='Upload MP4 file (max 100MB recommended)', null=True, upload_to='kenshi/videos/%Y/%m/%d/', verbose_name='video file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kenshi',
                'verbose_name_plural': 'kenjutsuka',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KenshiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kenjutsuka/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('kenshi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kenshi.kenshi', verbose_name='kenshi')),
            ],
            options={
                'verbose_name': 'kenshi image',
                'verbose_name_plural': 'kenshi images',
                'ordering': ['order'],
            },
        ),
    ]
