# Generated by Django 5.2.7 on 2025-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenshi',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 file (max 100MB recommended)', null=True, upload_to='kenshi/videos/%Y/%m/%d/', verbose_name='video file'),
        ),
    ]
