# Generated by Django 5.2.7 on 2025-10-28 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('subtitle_1', models.CharField(blank=True, max_length=100, verbose_name='subtitle 1')),
                ('contents_1', models.TextField(blank=True, verbose_name='contents 1')),
                ('subtitle_2', models.CharField(blank=True, max_length=100, verbose_name='subtitle 2')),
                ('contents_2', models.TextField(blank=True, verbose_name='contents 2')),
                ('subtitle_3', models.CharField(blank=True, max_length=100, verbose_name='subtitle 3')),
                ('contents_3', models.TextField(blank=True, verbose_name='contents 3')),
                ('lat', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='longitude')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('map_id', models.CharField(blank=True, help_text='Google Maps Place ID or custom ID', max_length=100, verbose_name='map id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notices/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.notice', verbose_name='notice')),
            ],
            options={
                'verbose_name': 'notice image',
                'verbose_name_plural': 'notice images',
                'ordering': ['order'],
            },
        ),
    ]
