# Generated by Django 6.0 on 2026-02-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='banner image')),
                ('caption', models.CharField(blank=True, max_length=60, verbose_name='caption')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('contents_main', models.TextField(blank=True, verbose_name='contents main')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('contents_main', models.TextField(verbose_name='contents main')),
                ('subtitle_1', models.CharField(blank=True, max_length=40, verbose_name='subtitle 1')),
                ('contents_1', models.TextField(blank=True, verbose_name='contents 1')),
                ('subtitle_2', models.CharField(blank=True, max_length=40, verbose_name='subtitle 2')),
                ('contents_2', models.TextField(blank=True, verbose_name='contents 2')),
                ('lat', models.CharField(blank=True, max_length=20, verbose_name='latitude')),
                ('lng', models.CharField(blank=True, max_length=20, verbose_name='longitude')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('map_id', models.CharField(blank=True, max_length=100, verbose_name='map id')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='author')),
                ('content', models.TextField(verbose_name='contents')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=60, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.news', verbose_name='news images')),
            ],
            options={
                'verbose_name': 'news image',
                'verbose_name_plural': 'news images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=60, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.notice', verbose_name='notice images')),
            ],
            options={
                'verbose_name': 'notice image',
                'verbose_name_plural': 'notice images',
                'ordering': ['order'],
            },
        ),
    ]
