# Generated by Django 5.2.7 on 2025-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='longitude'),
        ),
    ]
