# Generated by Django 5.2.7 on 2025-10-28 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_notice_lat_alter_notice_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('contents_main', models.TextField(blank=True, verbose_name='contents main')),
                ('subtitle_1', models.CharField(blank=True, max_length=100, verbose_name='subtitle 1')),
                ('contents_1', models.TextField(blank=True, verbose_name='contents 1')),
                ('subtitle_2', models.CharField(blank=True, max_length=100, verbose_name='subtitle 2')),
                ('contents_2', models.TextField(blank=True, verbose_name='contents 2')),
                ('lat', models.CharField(blank=True, max_length=100, null=True, verbose_name='latitude')),
                ('lng', models.CharField(blank=True, max_length=100, null=True, verbose_name='longitude')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('map_id', models.CharField(blank=True, help_text='Google Maps Place ID or custom ID', max_length=100, verbose_name='map id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'newses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newses/%Y/%m/%d/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'news image',
                'verbose_name_plural': 'news images',
                'ordering': ['order'],
            },
        ),
    ]
