# Generated by Django 6.0 on 2026-01-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About us', max_length=200, verbose_name='about_title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='about_subtitle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='about_description')),
                ('ending', models.TextField(blank=True, null=True, verbose_name='about_ending')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact', max_length=200, verbose_name='contact_title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='contact_subtitle')),
                ('person', models.CharField(blank=True, max_length=200, null=True, verbose_name='contact_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='contact_description')),
                ('ending', models.TextField(blank=True, null=True, verbose_name='contact_ending')),
            ],
            options={
                'verbose_name': 'contact Section',
                'verbose_name_plural': 'contact Sections',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FAQ', max_length=200, verbose_name='faq_title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='faq_subtitle')),
                ('question', models.CharField(blank=True, max_length=500, null=True, verbose_name='faq_question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='faq_answer')),
            ],
            options={
                'verbose_name': 'Faq Section',
                'verbose_name_plural': 'Faq Sections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy', max_length=200, verbose_name='privacy_title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='privacy_description')),
                ('ending', models.TextField(blank=True, null=True, verbose_name='privacy_ending')),
            ],
            options={
                'verbose_name': 'Privacy Section',
                'verbose_name_plural': 'Privacy Sections',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms & Conditions', max_length=200, verbose_name='terms_title')),
                ('subtitle_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='terms_subtitle_1')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='terms_description_1')),
                ('subtitle_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='terms_subtitle_2')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='terms_description_2')),
            ],
            options={
                'verbose_name': 'Terms Section',
                'verbose_name_plural': 'Terms Sections',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(max_length=50, verbose_name='section_label')),
                ('sectno', models.CharField(max_length=50, verbose_name='section_number')),
                ('sectname', models.CharField(max_length=200, verbose_name='section_name')),
                ('sectdesc', models.TextField(blank=True, null=True, verbose_name='section_description')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='others.terms', verbose_name='related_terms')),
            ],
            options={
                'verbose_name': 'Terms Section Detail',
                'verbose_name_plural': 'Terms Section Details',
                'ordering': ['sectno'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=50, verbose_name='part_label')),
                ('partno', models.CharField(max_length=50, verbose_name='part_number')),
                ('partname', models.CharField(max_length=200, verbose_name='part_name')),
                ('partdesc', models.TextField(blank=True, null=True, verbose_name='part_description')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='others.terms', verbose_name='related_terms')),
            ],
            options={
                'verbose_name': 'Terms Part',
                'verbose_name_plural': 'Terms Parts',
                'ordering': ['partno'],
            },
        ),
    ]
