# Generated by Django 5.2.7 on 2025-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100, verbose_name='about_title')),
                ('about_subtitle', models.CharField(max_length=100, verbose_name='about_subtitle')),
                ('about_content', models.TextField(blank=True, verbose_name='about_content')),
                ('about_ending', models.TextField(blank=True, verbose_name='about_ending')),
            ],
        ),
    ]
