# Generated by Django 5.2.7 on 2025-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='privacy_content',
            field=models.TextField(blank=True, verbose_name='privacy_content'),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_ending',
            field=models.TextField(blank=True, verbose_name='privacy_ending'),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_title',
            field=models.CharField(default='Privacy', max_length=100, verbose_name='privacy_title'),
        ),
    ]
