# Generated by Django 5.2.7 on 2025-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_footer_privacy_content_footer_privacy_ending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='contact_subtitle',
            field=models.CharField(default='Contact Subtitle', max_length=100, verbose_name='contact_subtitle'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_title',
            field=models.CharField(default='Contact Title', max_length=100, verbose_name='contact_title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='faq_content',
            field=models.TextField(blank=True, default='FAQ Content', verbose_name='faq_content'),
        ),
        migrations.AddField(
            model_name='footer',
            name='faq_title',
            field=models.CharField(default='FAQ Title', max_length=100, verbose_name='faq_title'),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_subtitle',
            field=models.CharField(default='Terms Subtitle', max_length=100, verbose_name='terms_subtitle'),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_title',
            field=models.CharField(default='Terms Title', max_length=100, verbose_name='terms_title'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_content',
            field=models.TextField(blank=True, default='About Content', verbose_name='about_content'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_ending',
            field=models.TextField(blank=True, default='About Ending', verbose_name='about_ending'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_subtitle',
            field=models.CharField(default='About Subtitle', max_length=100, verbose_name='about_subtitle'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='about_title',
            field=models.CharField(default='About Title', max_length=100, verbose_name='about_title'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy_content',
            field=models.TextField(blank=True, default='Privacy Content', verbose_name='privacy_content'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy_ending',
            field=models.TextField(blank=True, default='Privacy Ending', verbose_name='privacy_ending'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='privacy_title',
            field=models.CharField(default='Privacy_Title', max_length=100, verbose_name='privacy_title'),
        ),
    ]
