# Generated by Django 5.2.7 on 2025-10-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_footer_contact_subtitle_footer_contact_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Title', max_length=200, verbose_name='about_title')),
                ('subtitle', models.CharField(default='About Subtitle', max_length=200, verbose_name='about_subtitle')),
                ('content', models.TextField(blank=True, default='About Content', verbose_name='about_content')),
                ('ending', models.TextField(blank=True, default='About Ending', verbose_name='about_ending')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Title', max_length=200, verbose_name='contact_title')),
                ('subtitle', models.CharField(default='Contact Subtitle', max_length=200, verbose_name='contact_subtitle')),
                ('name', models.CharField(default='Contact Name', max_length=200, verbose_name='contact_name')),
                ('content', models.TextField(blank=True, default='Contact Content', verbose_name='contact_content')),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Sections',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FAQ Title', max_length=200, verbose_name='faq_title')),
                ('subtitle', models.CharField(default='FAQ subtitle', max_length=200, verbose_name='faq_subtitle')),
                ('question', models.CharField(default='FAQ Question', max_length=500, verbose_name='faq_question')),
                ('answer', models.TextField(blank=True, default='FAQ Answer', verbose_name='faq_answer')),
            ],
            options={
                'verbose_name': 'Faq Section',
                'verbose_name_plural': 'Faq Sections',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Title', max_length=200, verbose_name='privacy_title')),
                ('content', models.TextField(blank=True, default='Privacy Content', verbose_name='privacy_content')),
                ('ending', models.TextField(blank=True, default='Privacy Ending', verbose_name='privacy_ending')),
            ],
            options={
                'verbose_name': 'Privacy Section',
                'verbose_name_plural': 'Privacy Sections',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms Title', max_length=200, verbose_name='terms_title')),
                ('subtitle', models.CharField(default='Terms Subtitle', max_length=200, verbose_name='terms_subtitle')),
                ('content', models.TextField(blank=True, default='Terms Content', verbose_name='terms_content')),
            ],
            options={
                'verbose_name': 'Terms Section',
                'verbose_name_plural': 'Terms Sections',
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
