# Generated by Django 5.2.7 on 2025-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_about_contact_faq_privacy_terms_delete_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['subtitle', '-id'], 'verbose_name': 'Faq Section', 'verbose_name_plural': 'Faq Sections'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='about_content'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ending',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='about_ending'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='about_subtitle'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About us', max_length=200, unique=True, verbose_name='about_title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='contact_content'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='contact_name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='contact_subtitle'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact', max_length=200, unique=True, verbose_name='contact_title'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='faq_answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='faq_question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='faq_subtitle'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='FAQ', max_length=200, unique=True, verbose_name='faq_title'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='content',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='privacy_content'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='ending',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='privacy_ending'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='title',
            field=models.CharField(default='Privacy', max_length=200, unique=True, verbose_name='privacy_title'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='content',
            field=models.TextField(blank=True, help_text='Optional', null=True, verbose_name='terms_content'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='terms_subtitle'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(default='Terms & Conditions', max_length=200, unique=True, verbose_name='terms_title'),
        ),
    ]
