# Generated by Django 5.2.7 on 2025-10-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_alter_faq_options_alter_about_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About us', max_length=200, verbose_name='about_title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact', max_length=200, verbose_name='contact_title'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='FAQ', max_length=200, verbose_name='faq_title'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='title',
            field=models.CharField(default='Privacy', max_length=200, verbose_name='privacy_title'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(default='Terms & Conditions', max_length=200, verbose_name='terms_title'),
        ),
    ]
