# Generated by Django 5.2.7 on 2025-10-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_alter_about_content_alter_about_ending_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
