# Generated by Django 5.2.7 on 2025-10-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='contact', max_length=200, verbose_name='contact_title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='contact_subtitle')),
                ('person', models.CharField(blank=True, max_length=200, null=True, verbose_name='contact_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='contact_description')),
                ('ending', models.TextField(blank=True, null=True, verbose_name='contact_ending')),
            ],
            options={
                'verbose_name': 'contact Section',
                'verbose_name_plural': 'contact Sections',
            },
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='content',
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='about_description'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='privacy_description'),
        ),
        migrations.AddField(
            model_name='terms',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='terms_description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='about_ending'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='about_subtitle'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='faq_answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='faq_question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='faq_subtitle'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='privacy_ending'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='terms_subtitle'),
        ),
    ]
