# Generated by Django 5.2.7 on 2025-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_contact_delete_contacts_remove_about_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact', max_length=200, verbose_name='contact_title'),
        ),
    ]
