# Generated by Django 5.2.7 on 2025-10-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_alter_contact_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=50, verbose_name='part_label')),
                ('partno', models.CharField(max_length=50, verbose_name='part_number')),
                ('partname', models.CharField(max_length=200, verbose_name='part_name')),
                ('partdesc', models.TextField(blank=True, null=True, verbose_name='part_description')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='others.terms', verbose_name='related_terms')),
            ],
            options={
                'verbose_name': 'Terms Part',
                'verbose_name_plural': 'Terms Parts',
                'ordering': ['partno'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(max_length=50, verbose_name='section_label')),
                ('sectno', models.CharField(max_length=50, verbose_name='section_number')),
                ('sectname', models.CharField(max_length=200, verbose_name='section_name')),
                ('sectdesc', models.TextField(blank=True, null=True, verbose_name='section_description')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='others.terms', verbose_name='related_terms')),
            ],
            options={
                'verbose_name': 'Terms Section Detail',
                'verbose_name_plural': 'Terms Section Details',
                'ordering': ['sectno'],
            },
        ),
    ]
