# Generated by Django 5.2.7 on 2025-10-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_part_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='description',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='terms',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='terms_description_1'),
        ),
        migrations.AddField(
            model_name='terms',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='terms_description_2'),
        ),
        migrations.AddField(
            model_name='terms',
            name='subtitle_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='terms_subtitle_1'),
        ),
        migrations.AddField(
            model_name='terms',
            name='subtitle_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='terms_subtitle_2'),
        ),
    ]
