# Generated by Django 5.2.7 on 2025-10-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_remove_terms_description_remove_terms_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-id'], 'verbose_name': 'Faq Section', 'verbose_name_plural': 'Faq Sections'},
        ),
    ]
