# Generated by Django 5.2.7 on 2025-10-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0013_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name': 'Faq Section', 'verbose_name_plural': 'Faq Sections'},
        ),
    ]
